name: Build

on:
  push:

env:
  PROJECT_ID: ctbur-me
  REGION: europe-west1
  SERVICE: ctbur-me
  IMAGE_NAME: server

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Go
        uses: actions/setup-go@1d76b952eb9246b03e20e15a9ef98c6d4af389ef
        with:
          go-version: "1.24.5"

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: "Authenticate to Google Cloud"
        if: github.ref_name == 'main'
        uses: "google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5"
        with:
          service_account: "github-actions-deployer@ctbur-me.iam.gserviceaccount.com"
          credentials_json: ${{ secrets.GHA_DEPLOYER_KEY }}

      - name: "Set up Cloud SDK"
        if: github.ref_name == 'main'
        uses: "google-github-actions/setup-gcloud@cb1e50a9932213ecece00a606661ae9ca44f3397"

      - name: Use gcloud as Docker credential helper
        if: github.ref_name == 'main'
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: "Build and push Docker image"
        if: github.ref_name == 'main'
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: "Deploy to Cloud Run"
        if: github.ref_name == 'main'
        uses: "google-github-actions/deploy-cloudrun@147732842f8a61ce9bd3b3f8e9f6597fe991ad65"
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
